#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 12, 2018 04:22:35 PM


import sys
from firebase import firebase as fb
from tkinter import messagebox

import adminhome


try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def adminloginvalidation():
    username= w.admin_username.get()
    password=w.admin_password.get()
    if username == "":
        messagebox.showerror("admin","please enter username")
    elif password == "":
        messagebox.showerror("admin","please enter password")
    else:
        fire = fb.FirebaseApplication("https://pythonwithvipul.firebaseio.com/pythonwithvipul", None)
        result=fire.get("pythonwithvipul","Admin")
        if result['username']==username:
            if result['password']==password :
                messagebox.showinfo("admin", "valid login")
            else:
                messagebox.showerror("admin","invalid password")
        else:
            messagebox.showerror("admin", "invalid username")

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import adminlogin
    adminlogin.vp_start_gui()


