#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 15, 2018 05:45:40 PM


import sys

from tkinter import messagebox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def admin_customer():
    print('_support.admin_customer')
    sys.stdout.flush()

def admin_dispatcher():
    print('_support.admin_dispatcher')
    sys.stdout.flush()

def admin_logout():
    ans = messagebox.askyesno("Admin Logout", "Logout Conformation")
    if ans:
        destroy_window()

def admin_product():
    print('_support.admin_product')
    sys.stdout.flush()

def admin_sales():
    print('_support.admin_sales')
    sys.stdout.flush()

def admin_stocker():
    import stockerpage
    stockerpage.vp_start_gui()

# if __name__ == '__main__':
#     import adminhome
#     adminhome.vp_start_gui()


