#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 12, 2018 11:54:17 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import adminlogin_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = adminlogin (root)
    adminlogin_support.init(root, top)
    root.mainloop()

w = None
def create_adminlogin(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = adminlogin (w)
    adminlogin_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_adminlogin():
    global w
    w.destroy()
    w = None


class adminlogin:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {DejaVu Sans} -size 15 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("394x324+373+176")
        top.title("adminlogin")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.05, rely=0.03, relheight=0.88, relwidth=0.93)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="10")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#beadd8")
        self.Frame1.configure(width=365)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.22, rely=0.07, height=38, width=186)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(background="#beadd8")
        self.Label1.configure(font=font9)
        self.Label1.configure(text='''adminlogin''')

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.05, rely=0.25, height=28, width=126)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(background="#beadd8")
        self.Label2.configure(font=font9)
        self.Label2.configure(text='''username''')

        self.Label2_1 = Label(self.Frame1)
        self.Label2_1.place(relx=0.05, rely=0.42, height=28, width=126)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(background="#beadd8")
        self.Label2_1.configure(font=font9)
        self.Label2_1.configure(text='''password''')

        self.admin_username = Entry(self.Frame1)
        self.admin_username.place(relx=0.52, rely=0.25, height=30, relwidth=0.37)

        self.admin_username.configure(background="white")
        self.admin_username.configure(font="TkFixedFont")
        self.admin_username.configure(selectbackground="#c4c4c4")

        self.admin_password = Entry(self.Frame1)
        self.admin_password.place(relx=0.51, rely=0.42, height=29, relwidth=0.38)

        self.admin_password.configure(background="white")
        self.admin_password.configure(font="TkFixedFont")
        self.admin_password.configure(selectbackground="#c4c4c4")

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.33, rely=0.63, height=33, width=120)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(background="#beadd8")
        self.Button1.configure(borderwidth="2")
        self.Button1.configure(command=adminlogin_support.adminloginvalidation)
        self.Button1.configure(text='''Login''')








