#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 15, 2018 05:51:09 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import adminhome_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = adminhome (root)
    adminhome_support.init(root, top)
    root.mainloop()

w = None
def create_adminhome(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = adminhome (w)
    adminhome_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_adminhome():
    global w
    w.destroy()
    w = None


class adminhome:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {DejaVu Sans} -size 15 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("324x385+431+140")
        top.title("A    dminHome")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.03, rely=0.03, relheight=0.95, relwidth=0.94)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="5")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#beadd8")
        self.Frame1.configure(width=305)

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.26, rely=0.11, height=26, width=163)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(background="#beadd8")
        self.Button1.configure(command=adminhome_support.admin_stocker)
        self.Button1.configure(font=font9)
        self.Button1.configure(text='''stocker''')

        self.Button1_1 = Button(self.Frame1)
        self.Button1_1.place(relx=0.26, rely=0.19, height=26, width=163)
        self.Button1_1.configure(activebackground="#d9d9d9")
        self.Button1_1.configure(background="#beadd8")
        self.Button1_1.configure(command=adminhome_support.admin_dispatcher)
        self.Button1_1.configure(font=font9)
        self.Button1_1.configure(text='''dispatcher''')

        self.Button1_2 = Button(self.Frame1)
        self.Button1_2.place(relx=0.26, rely=0.38, height=26, width=163)
        self.Button1_2.configure(activebackground="#d9d9d9")
        self.Button1_2.configure(background="#beadd8")
        self.Button1_2.configure(command=adminhome_support.admin_product)
        self.Button1_2.configure(font=font9)
        self.Button1_2.configure(text='''Our product''')

        self.Button1_3 = Button(self.Frame1)
        self.Button1_3.place(relx=0.26, rely=0.47, height=26, width=163)
        self.Button1_3.configure(activebackground="#d9d9d9")
        self.Button1_3.configure(background="#beadd8")
        self.Button1_3.configure(command=adminhome_support.admin_customer)
        self.Button1_3.configure(font=font9)
        self.Button1_3.configure(text='''Our customer''')

        self.Button1_4 = Button(self.Frame1)
        self.Button1_4.place(relx=0.26, rely=0.55, height=26, width=163)
        self.Button1_4.configure(activebackground="#d9d9d9")
        self.Button1_4.configure(background="#beadd8")
        self.Button1_4.configure(command=adminhome_support.admin_sales)
        self.Button1_4.configure(font=font9)
        self.Button1_4.configure(text='''Our Sales''')

        self.Button2 = Button(self.Frame1)
        self.Button2.place(relx=0.39, rely=0.71, height=36, width=97)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(background="#beadd8")
        self.Button2.configure(command=adminhome_support.admin_logout)
        self.Button2.configure(font=font9)
        self.Button2.configure(text='''Logout''')






if __name__ == '__main__':
    vp_start_gui()



