#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 14, 2018 03:31:27 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import dispatcherlogin_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = dispatcherlogin (root)
    dispatcherlogin_support.init(root, top)
    root.mainloop()

w = None
def create_dispatcherlogin(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = dispatcherlogin (w)
    dispatcherlogin_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_dispatcherlogin():
    global w
    w.destroy()
    w = None


class dispatcherlogin:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {DejaVu Sans} -size 15 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("285x249+549+131")
        top.title("dispatcherlogin")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=0.98, relwidth=0.96)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="5")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#beadd8")
        self.Frame1.configure(width=275)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.18, rely=0.08, height=28, width=186)
        self.Label1.configure(background="#beadd8")
        self.Label1.configure(font=font9)
        self.Label1.configure(text='''dispatcherlogin''')
        self.Label1.configure(width=186)

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.04, rely=0.29, height=28, width=116)
        self.Label2.configure(background="#beadd8")
        self.Label2.configure(font=font9)
        self.Label2.configure(text='''username''')
        self.Label2.configure(width=116)

        self.Label2_1 = Label(self.Frame1)
        self.Label2_1.place(relx=0.02, rely=0.45, height=28, width=126)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(background="#beadd8")
        self.Label2_1.configure(font=font9)
        self.Label2_1.configure(text='''password''')

        self.dispatcher_username = Entry(self.Frame1)
        self.dispatcher_username.place(relx=0.47, rely=0.3, height=20
                , relwidth=0.48)
        self.dispatcher_username.configure(background="white")
        self.dispatcher_username.configure(font="TkFixedFont")

        self.dispatcher_password = Entry(self.Frame1)
        self.dispatcher_password.place(relx=0.47, rely=0.46, height=20
                , relwidth=0.48)
        self.dispatcher_password.configure(background="white")
        self.dispatcher_password.configure(font="TkFixedFont")
        self.dispatcher_password.configure(selectbackground="#c4c4c4")
        self.dispatcher_password.configure(show="*")

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.33, rely=0.64, height=36, width=87)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(background="#beadd8")
        self.Button1.configure(command=dispatcherlogin_support.dispatcherloginvalidation)
        self.Button1.configure(font=font9)
        self.Button1.configure(text='''Login''')
        self.Button1.configure(width=87)






if __name__ == '__main__':
    vp_start_gui()



