#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 16, 2018 10:44:45 AM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Home_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Home (root)
    Home_support.init(root, top)
    root.mainloop()

w = None
def create_Home(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Home (w)
    Home_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Home():
    global w
    w.destroy()
    w = None


class Home:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("220x197+541+134")
        top.title("Home")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=0.99, relwidth=0.98)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="5")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#beadd8")
        self.Frame1.configure(width=215)

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.23, rely=0.15, height=26, width=97)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(background="#beadd8")
        self.Button1.configure(command=Home_support.open_admin_login)
        self.Button1.configure(text='''Admin''')

        self.Button1_1 = Button(self.Frame1)
        self.Button1_1.place(relx=0.23, rely=0.36, height=26, width=97)
        self.Button1_1.configure(activebackground="#d9d9d9")
        self.Button1_1.configure(background="#beadd8")
        self.Button1_1.configure(command=Home_support.open_stocker_login)
        self.Button1_1.configure(text='''Stocker''')

        self.Button1_2 = Button(self.Frame1)
        self.Button1_2.place(relx=0.23, rely=0.56, height=26, width=97)
        self.Button1_2.configure(activebackground="#d9d9d9")
        self.Button1_2.configure(background="#beadd8")
        self.Button1_2.configure(command=Home_support.open_dispatcher_login)
        self.Button1_2.configure(text='''Dispatcher''')






if __name__ == '__main__':
    vp_start_gui()



