#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 13, 2018 01:07:06 AM


import sys
from tkinter import messagebox
from firebase import firebase as fb

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def stocker_autogen_id():
    fire = fb.FirebaseApplication("https://merchant-application-e1450.firebaseio.com/merchant/stocker",None)
    result = fire.get("stocker",None)
    idno = ""
    if result == None:
        idno = "1001"
    else:
        for x in result:
            pass
        id = int(x)
        id = id + 1
        idno = str(id)

    return idno

def save_stocker():
    idno = stocker_autogen_id()
    name = w.stocker_name.get()
    cno = w.stocker_phone.get()
    password = w.stocker_password.get()

    if name == "":
        messagebox.showerror("Registration","Enter Name")
    elif cno == "":
        messagebox.showerror("Registration", "Enter Phone No")
    elif password == "":
        messagebox.showerror("Registration", "Enter Password")
    else:
        fire = fb.FirebaseApplication("https://merchant-application-e1450.firebaseio.com/merchant/stocker",None)
        fire.put("stocker",idno,{"name":name,"phone":cno,"password":password})
        messagebox.showinfo("Registration","Employee Saved")
        destroy_window()


def view_stocker():
    idno = w.view_stocker_id.get()
    if idno == "":
        messagebox.showerror("View","Enter Idno")
    else:
        fire = fb.FirebaseApplication("https://merchant-application-e1450.firebaseio.com/merchant/stocker",None)
        result = fire.get("stocker", idno)
        if result == None:
            messagebox.showerror("View","Invalid Idno")
            w.view_stocker_id.delete(0,"end")
        else:
            name = result["name"]
            pno = result["phone"]
            w.view_stockter_cno.configure(text=pno)
            w.view_stocker_name.configure(text=name)

if __name__ == '__main__':
    import stockerpage
    stockerpage.vp_start_gui()