#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Jun 13, 2018 06:19:43 PM

import sys


try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import stockerpage_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = stockerpage (root)
    stockerpage_support.init(root, top)
    root.mainloop()

w = None
def create_Stockerpage(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Stockerpage (w)
    stockerpage_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Stockerpage():
    global w
    w.destroy()
    w = None


class Stockerpage:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {DejaVu Sans} -size 15 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("575x308+536+132")
        top.title("Stockerpage")
        top.configure(highlightcolor="black")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.02, rely=0.03, relheight=0.93, relwidth=0.44)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="5")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#beadd8")
        self.Frame1.configure(width=255)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.04, rely=0.04, height=28, width=234)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(background="#beadd8")
        self.Label1.configure(font=font9)
        self.Label1.configure(text='''StockerRegistration''')

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.04, rely=0.15, height=30, width=91)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(background="#beadd8")
        self.Label2.configure(font=font9)
        self.Label2.configure(text='''Id no''')


        self.Label3 = Label(self.Frame1)
        self.Label3.place(relx=0.02, rely=0.29, height=29, width=109)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(background="#beadd8")
        self.Label3.configure(font=font9)
        self.Label3.configure(text='''Name''')

        self.Label4 = Label(self.Frame1)
        self.Label4.place(relx=0.04, rely=0.42, height=29, width=110)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(background="#beadd8")
        self.Label4.configure(font=font9)
        self.Label4.configure(text='''Contact''')

        self.Label5 = Label(self.Frame1)
        self.Label5.place(relx=0.04, rely=0.53, height=31, width=110)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(background="#beadd8")
        self.Label5.configure(font=font9)
        self.Label5.configure(text='''Password''')

        self.admin_stocker_id = Entry(self.Frame1)
        self.admin_stocker_id.place(relx=0.49, rely=0.14, height=24
                , relwidth=0.42)
        self.admin_stocker_id.configure(background="white")
        self.admin_stocker_id.configure(font="TkFixedFont")
        self.admin_stocker_id.configure(selectbackground="#c4c4c4")
        self.admin_stocker_id.configure(show="....")

        self.admin_stocker_name = Entry(self.Frame1)
        self.admin_stocker_name.place(relx=0.49, rely=0.28, height=26
                , relwidth=0.43)
        self.admin_stocker_name.configure(background="white")
        self.admin_stocker_name.configure(font="TkFixedFont")
        self.admin_stocker_name.configure(selectbackground="#c4c4c4")

        self.admin_stocker_contact = Entry(self.Frame1)
        self.admin_stocker_contact.place(relx=0.49, rely=0.42, height=25
                , relwidth=0.44)
        self.admin_stocker_contact.configure(background="white")
        self.admin_stocker_contact.configure(font="TkFixedFont")
        self.admin_stocker_contact.configure(selectbackground="#c4c4c4")

        self.admin_stocker_password = Entry(self.Frame1)
        self.admin_stocker_password.place(relx=0.49, rely=0.54, height=26
                , relwidth=0.43)
        self.admin_stocker_password.configure(background="white")
        self.admin_stocker_password.configure(font="TkFixedFont")
        self.admin_stocker_password.configure(selectbackground="#c4c4c4")
        self.admin_stocker_password.configure(show="*")

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.31, rely=0.74, height=36, width=97)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(background="#beadd8")
        self.Button1.configure(command=stockerpage_support.RegisterStocker)
        self.Button1.configure(font=font9)
        self.Button1.configure(text='''Save''')

        self.Frame2 = Frame(top)
        self.Frame2.place(relx=0.47, rely=0.03, relheight=0.93, relwidth=0.48)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="5")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#beadd8")
        self.Frame2.configure(width=265)

        self.Label6 = Label(self.Frame2)
        self.Label6.place(relx=0.07, rely=0.04, height=28, width=216)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(background="#beadd8")
        self.Label6.configure(font=font9)
        self.Label6.configure(text='''StockerView''')

        self.Label7 = Label(self.Frame2)
        self.Label7.place(relx=0.07, rely=0.14, height=28, width=86)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(background="#beadd8")
        self.Label7.configure(font=font9)
        self.Label7.configure(text='''Id no''')

        self.Label8 = Label(self.Frame2)
        self.Label8.place(relx=0.04, rely=0.28, height=24, width=109)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(background="#beadd8")
        self.Label8.configure(font=font9)
        self.Label8.configure(text='''Name''')

        self.Label9 = Label(self.Frame2)
        self.Label9.place(relx=0.07, rely=0.41, height=26, width=96)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(background="#beadd8")
        self.Label9.configure(font=font9)
        self.Label9.configure(text='''Contact''')

        self.Label10 = Label(self.Frame2)
        self.Label10.place(relx=0.07, rely=0.54, height=28, width=106)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(background="#beadd8")
        self.Label10.configure(font=font9)
        self.Label10.configure(text='''Password''')

        self.stocker_view_id = Entry(self.Frame2)
        self.stocker_view_id.place(relx=0.47, rely=0.15, height=23
                , relwidth=0.45)
        self.stocker_view_id.configure(background="white")
        self.stocker_view_id.configure(font="TkFixedFont")
        self.stocker_view_id.configure(selectbackground="#c4c4c4")

        self.stocker_view_name = Entry(self.Frame2)
        self.stocker_view_name.place(relx=0.47, rely=0.27, height=23
                , relwidth=0.45)
        self.stocker_view_name.configure(background="white")
        self.stocker_view_name.configure(font="TkFixedFont")
        self.stocker_view_name.configure(selectbackground="#c4c4c4")

        self.stocker_view_contact = Entry(self.Frame2)
        self.stocker_view_contact.place(relx=0.47, rely=0.4, height=23
                , relwidth=0.45)
        self.stocker_view_contact.configure(background="white")
        self.stocker_view_contact.configure(font="TkFixedFont")
        self.stocker_view_contact.configure(selectbackground="#c4c4c4")

        self.stocker_view_password = Entry(self.Frame2)
        self.stocker_view_password.place(relx=0.49, rely=0.53, height=24
                , relwidth=0.44)
        self.stocker_view_password.configure(background="white")
        self.stocker_view_password.configure(font="TkFixedFont")
        self.stocker_view_password.configure(selectbackground="#c4c4c4")
        self.stocker_view_password.configure(show="*")

        self.Button2 = Button(self.Frame2)
        self.Button2.place(relx=0.33, rely=0.7, height=38, width=109)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(background="#beadd8")
        self.Button2.configure(font=font9)
        self.Button2.configure(text='''Show''')






if __name__ == '__main__':
    vp_start_gui()



